# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\codes\uga\projectCEBD-2021\gui\add_fct_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RepSansRes(object):
    def setupUi(self, RepSansRes):
        RepSansRes.setObjectName("RepSansRes")
        RepSansRes.resize(603, 304)
        self.verticalLayoutWidget = QtWidgets.QWidget(RepSansRes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableListeRepresentations = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableListeRepresentations.setObjectName("tableListeRepresentations")
        self.tableListeRepresentations.setColumnCount(4)
        self.tableListeRepresentations.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableListeRepresentations.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListeRepresentations.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListeRepresentations.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListeRepresentations.setHorizontalHeaderItem(3, item)
        self.tableListeRepresentations.horizontalHeader().setDefaultSectionSize(144)
        self.tableListeRepresentations.horizontalHeader().setStretchLastSection(True)
        self.tableListeRepresentations.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableListeRepresentations)
        self.label_rep_res = QtWidgets.QLabel(RepSansRes)
        self.label_rep_res.setGeometry(QtCore.QRect(10, 280, 581, 16))
        self.label_rep_res.setText("")
        self.label_rep_res.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rep_res.setObjectName("label_rep_res")

        self.retranslateUi(RepSansRes)
        QtCore.QMetaObject.connectSlotsByName(RepSansRes)

    def retranslateUi(self, RepSansRes):
        _translate = QtCore.QCoreApplication.translate
        RepSansRes.setWindowTitle(_translate("RepSansRes", "Représentations sans réservations"))
        item = self.tableListeRepresentations.horizontalHeaderItem(0)
        item.setText(_translate("RepSansRes", "noSpec"))
        item = self.tableListeRepresentations.horizontalHeaderItem(1)
        item.setText(_translate("RepSansRes", "nomSpec"))
        item = self.tableListeRepresentations.horizontalHeaderItem(2)
        item.setText(_translate("RepSansRes", "noRep"))
        item = self.tableListeRepresentations.horizontalHeaderItem(3)
        item.setText(_translate("RepSansRes", "dateRep"))
