# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\codes\uga\projectCEBD-2021\gui\fct_comp_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fct_comp_2(object):
    def setupUi(self, fct_comp_2):
        fct_comp_2.setObjectName("fct_comp_2")
        fct_comp_2.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(fct_comp_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_categorie = QtWidgets.QComboBox(fct_comp_2)
        self.comboBox_categorie.setObjectName("comboBox_categorie")
        self.comboBox_categorie.addItem("")
        self.verticalLayout.addWidget(self.comboBox_categorie)
        self.table_fct_comp_2 = QtWidgets.QTableWidget(fct_comp_2)
        self.table_fct_comp_2.setObjectName("table_fct_comp_2")
        self.table_fct_comp_2.setColumnCount(3)
        self.table_fct_comp_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_2.setHorizontalHeaderItem(2, item)
        self.table_fct_comp_2.horizontalHeader().setMinimumSectionSize(50)
        self.table_fct_comp_2.horizontalHeader().setStretchLastSection(True)
        self.table_fct_comp_2.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_fct_comp_2)
        self.label_fct_comp_2 = QtWidgets.QLabel(fct_comp_2)
        self.label_fct_comp_2.setText("")
        self.label_fct_comp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fct_comp_2.setObjectName("label_fct_comp_2")
        self.verticalLayout.addWidget(self.label_fct_comp_2)

        self.retranslateUi(fct_comp_2)
        QtCore.QMetaObject.connectSlotsByName(fct_comp_2)

    def retranslateUi(self, fct_comp_2):
        _translate = QtCore.QCoreApplication.translate
        fct_comp_2.setWindowTitle(_translate("fct_comp_2", "Liste des places d\'une catégorie (version 2)"))
        self.comboBox_categorie.setItemText(0, _translate("fct_comp_2", "Choisir une catégorie"))
        item = self.table_fct_comp_2.horizontalHeaderItem(0)
        item.setText(_translate("fct_comp_2", "noPlace"))
        item = self.table_fct_comp_2.horizontalHeaderItem(1)
        item.setText(_translate("fct_comp_2", "noRang"))
        item = self.table_fct_comp_2.horizontalHeaderItem(2)
        item.setText(_translate("fct_comp_2", "noZone"))
