# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\codes\uga\projectCEBD-2021\gui\fct_comp_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fct_comp_1(object):
    def setupUi(self, fct_comp_1):
        fct_comp_1.setObjectName("fct_comp_1")
        fct_comp_1.resize(600, 300)
        fct_comp_1.setWindowOpacity(9.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(fct_comp_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_categorie = QtWidgets.QComboBox(fct_comp_1)
        self.comboBox_categorie.setEnabled(True)
        self.comboBox_categorie.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_categorie.setObjectName("comboBox_categorie")
        self.comboBox_categorie.addItem("")
        self.comboBox_categorie.addItem("")
        self.comboBox_categorie.addItem("")
        self.comboBox_categorie.addItem("")
        self.verticalLayout.addWidget(self.comboBox_categorie)
        self.table_fct_comp_1 = QtWidgets.QTableWidget(fct_comp_1)
        self.table_fct_comp_1.setObjectName("table_fct_comp_1")
        self.table_fct_comp_1.setColumnCount(3)
        self.table_fct_comp_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_1.setHorizontalHeaderItem(2, item)
        self.table_fct_comp_1.horizontalHeader().setMinimumSectionSize(50)
        self.table_fct_comp_1.horizontalHeader().setStretchLastSection(True)
        self.table_fct_comp_1.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_fct_comp_1)
        self.label_fct_comp_1 = QtWidgets.QLabel(fct_comp_1)
        self.label_fct_comp_1.setText("")
        self.label_fct_comp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fct_comp_1.setObjectName("label_fct_comp_1")
        self.verticalLayout.addWidget(self.label_fct_comp_1)

        self.retranslateUi(fct_comp_1)
        QtCore.QMetaObject.connectSlotsByName(fct_comp_1)

    def retranslateUi(self, fct_comp_1):
        _translate = QtCore.QCoreApplication.translate
        fct_comp_1.setWindowTitle(_translate("fct_comp_1", "Liste des places d\'une catégorie (version 1)"))
        self.comboBox_categorie.setItemText(0, _translate("fct_comp_1", "Choisir une catégorie"))
        self.comboBox_categorie.setItemText(1, _translate("fct_comp_1", "orchestre"))
        self.comboBox_categorie.setItemText(2, _translate("fct_comp_1", "balcon"))
        self.comboBox_categorie.setItemText(3, _translate("fct_comp_1", "poulailler"))
        item = self.table_fct_comp_1.horizontalHeaderItem(0)
        item.setText(_translate("fct_comp_1", "noPlace"))
        item = self.table_fct_comp_1.horizontalHeaderItem(1)
        item.setText(_translate("fct_comp_1", "noRang"))
        item = self.table_fct_comp_1.horizontalHeaderItem(2)
        item.setText(_translate("fct_comp_1", "noZone"))
