# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\codes\uga\projectCEBD-2021\gui\imp_fct_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gererRep(object):
    def setupUi(self, gererRep):
        gererRep.setObjectName("gererRep")
        gererRep.resize(639, 399)
        self.verticalLayoutWidget = QtWidgets.QWidget(gererRep)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 65, 341, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableRep = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableRep.setObjectName("tableRep")
        self.tableRep.setColumnCount(0)
        self.tableRep.setRowCount(0)
        self.verticalLayout.addWidget(self.tableRep)
        self.comboBox_spectacle = QtWidgets.QComboBox(gererRep)
        self.comboBox_spectacle.setGeometry(QtCore.QRect(11, 15, 341, 31))
        self.comboBox_spectacle.setObjectName("comboBox_spectacle")
        self.comboBox_spectacle.addItem("")
        self.addRep = QtWidgets.QPushButton(gererRep)
        self.addRep.setGeometry(QtCore.QRect(525, 355, 93, 28))
        self.addRep.setObjectName("addRep")
        self.doubleSpinBox_promoRep = QtWidgets.QDoubleSpinBox(gererRep)
        self.doubleSpinBox_promoRep.setGeometry(QtCore.QRect(535, 275, 81, 31))
        self.doubleSpinBox_promoRep.setObjectName("doubleSpinBox_promoRep")
        self.dateTimeEdit_dateRep = QtWidgets.QDateTimeEdit(gererRep)
        self.dateTimeEdit_dateRep.setGeometry(QtCore.QRect(475, 315, 141, 31))
        self.dateTimeEdit_dateRep.setObjectName("dateTimeEdit_dateRep")
        self.label_promoRep = QtWidgets.QLabel(gererRep)
        self.label_promoRep.setGeometry(QtCore.QRect(371, 275, 81, 31))
        self.label_promoRep.setObjectName("label_promoRep")
        self.label_dateRep = QtWidgets.QLabel(gererRep)
        self.label_dateRep.setGeometry(QtCore.QRect(371, 315, 101, 31))
        self.label_dateRep.setObjectName("label_dateRep")
        self.label_representation = QtWidgets.QLabel(gererRep)
        self.label_representation.setGeometry(QtCore.QRect(371, 222, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.label_representation.setFont(font)
        self.label_representation.setObjectName("label_representation")
        self.label_spectacle = QtWidgets.QLabel(gererRep)
        self.label_spectacle.setGeometry(QtCore.QRect(371, 52, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.label_spectacle.setFont(font)
        self.label_spectacle.setObjectName("label_spectacle")
        self.doubleSpinBox_prixSpec = QtWidgets.QDoubleSpinBox(gererRep)
        self.doubleSpinBox_prixSpec.setGeometry(QtCore.QRect(531, 152, 91, 22))
        self.doubleSpinBox_prixSpec.setObjectName("doubleSpinBox_prixSpec")
        self.lineEdit_nomSpec = QtWidgets.QLineEdit(gererRep)
        self.lineEdit_nomSpec.setGeometry(QtCore.QRect(433, 112, 191, 22))
        self.lineEdit_nomSpec.setObjectName("lineEdit_nomSpec")
        self.label_nomSpec = QtWidgets.QLabel(gererRep)
        self.label_nomSpec.setGeometry(QtCore.QRect(371, 112, 55, 21))
        self.label_nomSpec.setObjectName("label_nomSpec")
        self.label_prixSpec = QtWidgets.QLabel(gererRep)
        self.label_prixSpec.setGeometry(QtCore.QRect(371, 152, 55, 16))
        self.label_prixSpec.setObjectName("label_prixSpec")
        self.addSpec = QtWidgets.QPushButton(gererRep)
        self.addSpec.setGeometry(QtCore.QRect(530, 190, 93, 28))
        self.addSpec.setObjectName("addSpec")

        self.retranslateUi(gererRep)
        QtCore.QMetaObject.connectSlotsByName(gererRep)

    def retranslateUi(self, gererRep):
        _translate = QtCore.QCoreApplication.translate
        gererRep.setWindowTitle(_translate("gererRep", "Gérer les représentations"))
        self.comboBox_spectacle.setItemText(0, _translate("gererRep", "Sélectionner un spectacle"))
        self.addRep.setText(_translate("gererRep", "Créer"))
        self.label_promoRep.setText(_translate("gererRep", "Promotion :"))
        self.label_dateRep.setText(_translate("gererRep", "Date / heure :"))
        self.label_representation.setText(_translate("gererRep", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Ajouter une représentation</span></p></body></html>"))
        self.label_spectacle.setText(_translate("gererRep", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Ajouter un spectacle</span></p></body></html>"))
        self.label_nomSpec.setText(_translate("gererRep", "Nom :"))
        self.label_prixSpec.setText(_translate("gererRep", "Prix :"))
        self.addSpec.setText(_translate("gererRep", "Créer"))
